[package]
name = "gpn-mazing-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
rand = "0.8.5"
float-ord = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
image = "0.24.2"
petgraph = "0.6.5"
